# -*- coding: utf-8 -*-
"""Multiagentes.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qGaMUN0Qq-Hu86c25vtEE_UriPCwGDAu
"""

# !pip3 install control

import random

class Agente:
    def __init__(self, nome):
        self.nome = nome

    def enviar_mensagem(self, destinatario, mensagem):
        destinatario.receber_mensagem(self, mensagem)

    def receber_mensagem(self, remetente, mensagem):
        pass

class Requerente(Agente):
    def __init__(self, nome):
        super().__init__(nome)
        self.melhor_custo = None

    def receber_mensagem(self, remetente, mensagem):
        if self.melhor_custo is None or mensagem < self.melhor_custo:
            self.melhor_custo = mensagem
            print(f"{self.nome}: Recebi um novo custo: {mensagem} do {remetente.nome}")

class Executor(Agente):
    def __init__(self, nome):
        super().__init__(nome)

    def enviar_custo(self, requerente):
        custo = random.randint(1, 100)
        print(f"{self.nome}: Enviei um custo de {custo} ao {requerente.nome}")
        requerente.receber_mensagem(self, custo)

# Criando os agentes
requerente = Requerente("Requerente")
executor1 = Executor("Executor 1")
executor2 = Executor("Executor 2")

# Simulando a negociação
executor1.enviar_custo(requerente)
executor2.enviar_custo(requerente)

print(f"\n{requerente.nome}: O melhor custo recebido foi {requerente.melhor_custo}")